#!/usr/bin/python

import os
import time
import datetime

now = int(time.time());

with open(os.path.expanduser('~/.tracker/current'), 'w+') as file:
    file.write(str(now))

print('Started working at %s' % datetime.datetime.utcfromtimestamp(now))
